[package]
name = "rust_python_ffi_example"
version = "0.1.0"
authors = ["James Kominick <james.kominick@gmail.com>"]

[dependencies]
libc = "*"

[lib]
name = "rust_python_ffi_example"
crate-type = ["rlib", "dylib"]
